### ISSUE TITLE
Failed to fetch workspaces -  invalid memory address

### ISSUE THREAD

**Issue by alzaaba6** [maxlandon/wiregost#1]
Hi,

Running binaries on OSX and Linux, I get same error message of failed to fetch workspaces, error below.

Thanks!
--------
exit status 2
Failed to fetch workspaces
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x159d49f]

goroutine 1 [running]:
github.com/maxlandon/wiregost/client/console.(*Console).initContext(0xc000106dc0)
	/home/para/.pentest/wiregost/client/console/context.go:44 +0x9f
github.com/maxlandon/wiregost/client/console.newConsole(0x1708c28)
	/home/para/.pentest/wiregost/client/console/console.go:89 +0x10f
github.com/maxlandon/wiregost/client/console.Start()
	/home/para/.pentest/wiregost/client/console/console.go:143 +0x37
main.main()
	/home/para/.pentest/wiregost/client/wiregost-console.go:54 +0x3c0

**Comment by maxlandon** [comment]
Hello @alzaaba6,

Did you make sure the Data-Service binary is running ? With PostgreSQL installed and with access to user postgres ?
Otherwise the console will not work.
